version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/src
    depends_on:
      - database
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db-init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
volumes:
  db_data:
